package api

import (
	_ "embed"
	"net/http"
)

// openAPISpec is generated by docs/gen_openapi.py.
//
//go:embed openapi.json
var openAPISpec []byte

// openAPI serves the machine-readable description of this API.
func (a *API) openAPI(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "public, max-age=300")
	_, _ = w.Write(openAPISpec)
}
